### ISSUE TITLE
Errors trying to build with C++20

### ISSUE THREAD

**Issue by elanhickler** [surge-synthesizer/conduit#90]
When I try to switch conduit to build with C++20, I get errors.

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2679	binary '<<': no operator found which takes a right-hand operand of type 'std::basic_string<char8_t,std::char_traits<char8_t>,std::allocator<char8_t>>' (or there is no acceptable conversion)	conduit-impl	F:\(PROGRAMMING)\clapconduithydrus\src\conduit-shared\clap-base-class.h	604
```cpp
if (operation == SAVE)
              {
                  std::ofstream ofs(fsp, std::ios::out | std::ios::binary);
                  if (!ofs.is_open())
                  {
                      CNDOUT << "Unable to open for writing " << fsp.u8string() << std::endl;
                      return;
                  }
                  CNDOUT << "Writing patch to " << fsp.u8string() << std::endl;
                  clap_ostream cos{};
                  cos.ctx = &ofs;
                  cos.write = clapwrite;
                  that.stateSave(&cos);
                  ofs.close();
              }
```

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2440	'return': cannot convert from 'std::basic_string<char8_t,std::char_traits<char8_t>,std::allocator<char8_t>>' to 'std::basic_string<char,std::char_traits<char>,std::allocator<char>>'	conduit-impl	F:\(PROGRAMMING)\clapconduithydrus\build\libs\sst\sst-plugininfra\libs\filesystem\include\filesystem\import.h	21	
```cpp
inline std::string path_to_string(const fs::path& path)
{
#ifdef _WIN32
   return path.u8string();
#else
   return path.generic_string();
#endif
}
```

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2088	'<<': illegal for class	conduit-impl	F:\(PROGRAMMING)\clapconduithydrus\src\conduit-shared\clap-base-class.h	607	
```cpp
if (!ifs.is_open())
{
    CNDOUT << "Unable to open for reading " << fsp.u8string() << std::endl;
    return;
}
```

**Comment by baconpaul** [comment]
To build with C++20 you need the utf8 string fix.

```
$<$<COMPILE_LANGUAGE:CXX>:-fno-char8_t>
```

add that to the compile options or better add it if the version >= 20

**Comment by baconpaul** [comment]
https://github.com/surge-synthesizer/surge/blob/4b53827e05959ab33a1787bd81cfacf190c843d3/CMakeLists.txt#L92C5-L92C44

**Comment by baconpaul** [comment]
(the c++20 insistence that a utf8 char and a char are not the same is a huge clusterf**k by the way, which is mostly fixed in 23; that flag turns it off)

**Comment by elanhickler** [comment]
which cmake file do you add this to? i tried the one in src and the one in the main folder already, I saw no changes in errors.

I also changed the line `set(CMAKE_CXX_STANDARD 20)` so it would be 20 instead of 17

**Comment by baconpaul** [comment]
I just pushed them in in [b1cc695](https://github.com/surge-synthesizer/conduit/commit/b1cc69594c1fc56472cd055927425602e27db9f0)

if you pull that then set standard to 20 it will build all platforms.
